version: '3.7'

services:
  api:
    build: ./api
    image: 074682543290.dkr.ecr.ap-northeast-1.amazonaws.com/aws-multi-container-example-api
#    image: web-api
    container_name: node-web-api
    ports:
      - "3001:3001"
  web:
    build: ./web
    image: 074682543290.dkr.ecr.ap-northeast-1.amazonaws.com/aws-multi-container-example-web
#    image: web-app
    container_name: node-web-app
    ports:
      - "3000:3000"
